#!/usr/bin/env python3
"""
Hướng dẫn sử dụng GitHub Copilot với ITM Translate
"""

print("=== 🤖 HƯỚNG DẪN GITHUB COPILOT CHO ITM TRANSLATE ===\n")

print("🚨 LƯU Ý QUAN TRỌNG:")
print("━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━")
print()

print("❌ GitHub Personal Access Token KHÔNG THỂ SỬ DỤNG:")
print("   • Token từ https://github.com/settings/tokens (ghp_xxx, gho_xxx)")
print("   • Không hoạt động với translation API calls")
print("   • Sẽ báo lỗi 401 Invalid API key")
print()

print("✅ SỬ DỤNG OPENAI API KEY:")
print("   • Cần OpenAI API key (sk-xxx) từ https://platform.openai.com/api-keys")
print("   • GitHub Copilot provider sẽ dùng OpenAI API với Copilot personality")
print("   • Hoạt động với models: gpt-4, gpt-3.5-turbo, copilot-codex")
print()

print("📋 CÁCH LẤY OPENAI API KEY:")
print("━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━")
print("1. Truy cập: https://platform.openai.com/api-keys")
print("2. Đăng nhập bằng tài khoản OpenAI")
print("3. Click 'Create new secret key'")
print("4. Đặt tên cho key (ví dụ: 'ITM Translate Copilot')")
print("5. Copy API key (bắt đầu bằng 'sk-')")
print("6. Lưu trữ an toàn - không chia sẻ công khai")
print()

print("🎯 CÁCH SỬ DỤNG TRONG ITM TRANSLATE:")
print("━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━")
print("1. Mở ITM Translate → tab 'Quản lý API KEY'")
print("2. Provider dropdown → chọn 'copilot'")
print("3. Model dropdown → chọn 'gpt-4' (khuyến nghị)")
print("4. API Key field → nhập OpenAI API key (sk-xxx)")
print("5. Click 'Thêm Key'")
print("6. Bắt đầu dịch với GitHub Copilot personality! 🤖")
print()

print("💰 CHI PHÍ & PRICING:")
print("━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━")
print("• OpenAI API có pricing theo usage")
print("• GPT-4: ~$0.03/1K tokens input, ~$0.06/1K tokens output")
print("• GPT-3.5 Turbo: ~$0.0015/1K tokens input, ~$0.002/1K tokens output")
print("• Có free tier để test: $5 credit khi đăng ký mới")
print("• Chi phí translation rất thấp cho hầu hết use cases")
print()

print("🔧 TẠI SAO KHÔNG DÙNG GITHUB TOKEN?")
print("━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━")
print("• GitHub Personal Access Token chỉ dùng cho Git operations")
print("• GitHub Copilot không có public translation API")
print("• GitHub Copilot trong VS Code dùng internal endpoints")
print("• OpenAI API là cách duy nhất để access GPT models for translation")
print()

print("🌟 LỢI ÍCH CỦA GITHUB COPILOT PROVIDER:")
print("━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━")
print("• 🤖 Copilot personality - chuyên về technical content")
print("• 💻 Tuyệt vời cho code comments, technical docs")
print("• 🎯 High-quality translation với GPT-4")
print("• ⚡ Fast response với GPT-3.5 Turbo")
print("• 🔄 Failover automatic sang providers khác nếu cần")
print()

print("❓ FAQ:")
print("━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━")
print("Q: Tôi có GitHub Copilot subscription, có dùng được không?")
print("A: Subscription GitHub Copilot chỉ cho VS Code, không cho API calls.")
print("   Vẫn cần OpenAI API key riêng cho ITM Translate.")
print()
print("Q: GitHub token báo lỗi 401, làm sao?")
print("A: GitHub token không dùng được. Hãy dùng OpenAI API key thay thế.")
print()
print("Q: OpenAI API key có an toàn không?")
print("A: Có, nhưng không chia sẻ công khai. ITM Translate lưu trữ local.")
print()

print("🎉 KẾT LUẬN:")
print("━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━")
print("GitHub Copilot provider hoạt động tốt với OpenAI API key!")
print("Đây là cách duy nhất để có GitHub Copilot personality trong ITM Translate.")
print("Hãy thử ngay với free $5 credit từ OpenAI! 🚀")
print()
print("💭 GitHub Copilot: 'Ready to help with translation using OpenAI API! 🤖✨'")
